version: '2'
services:
    manga_crawler-mysql:
        container_name: manga_crawler-mysql
        image: mysql:5.7.12
        # volumes:
        #     - ~/volumes/jhipster/manga_crawler/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=manga_crawler
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
